version: '3.9'

services:
  # Servicio de aplicación
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: unless-stopped
    # No definimos dependencia a base de datos porque se usa Neon DB (servicio externo)
    
  # Servicio para migraciones de Prisma
  prisma-migrate:
    build:
      context: .
      dockerfile: prisma-migrate.Dockerfile
    env_file:
      - .env.production
    depends_on:
      - app 